### PR TITLE
update canvas (mrt & wolvhaven)

### PR DESCRIPTION
**Pull request by iiiii7d**
Canvas updates
- MRT migrated to new position
- Wolvhaven settled next to us

thanks :D

### CODE REVIEW

**Comment by quexpexx** [comment]
This overlay gets its data from `template.png`, which is an image 3x larger than  `canvas.png`. `canvas.png` represents the entire canvas, `template.png` is every pixel in the canvas surrounded by transparent pixels, in order to make a 3x3 grid. You can generate a `templete.png` from `canvas.png` if you run `expandpixels.py`. Then upload both `canvas.png` and `template.png` to keep things consistent between them.  
I'd recommend testing your fork after uploading `template.png` by modifying your userscript to point it to *your* fork's `template.png`.  
After that, report back if it works and I'll merge it.  
Thanks.

**Comment by quexpexx** [comment]
You tested it and everything is aligned properly, correct? I cannot test as I'm on mobile at the moment.

**Comment by quexpexx** [comment]
Thank you, merging.

**Comment by iiiii7d** [comment]
thanks too :)

**Pull request merged**
