### PR TITLE
Include Furry Sections

### PR DESCRIPTION
**Pull request by Russec**
Hi there, I *think* this should have our pixel overlay merged with yours. I checked locally and it looks okay, but you may want to check as well.

### CODE REVIEW

**Comment by quexpexx** [comment]
Hello, this wouldn't merge the sections properly, because `template.png` is supposed to be a 6000x3000 image (3x bigger than `canvas.png`, which is the entire canvas). It's supposed to place a smaller pixel in the middle of a tile so it becomes obvious which color to put back when rebuilding. I have 2 python scripts to generate `template.png` from `canvas.png` and vice versa. To fix your PR, you should move the `template.png` file you commited into `canvas.png` and then run `expandpixels.py`, which should generate a `template.py` from the canvas.

**Comment by Russec** [comment]
oh sure, we have that format, too.

**Comment by Russec** [comment]
@quexpexx done.

**Comment by quexpexx** [comment]
Thanks, I'll add a commit after I merge to generate `canvas.png` out of `template.png` just to keep them consistent among each other.

**Comment by quexpexx** [comment]
tested it by merging it lol, everything works, thank you

**Pull request merged**
